spring:
  main:
    web-application-type: NONE
    banner-mode: OFF
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pomodoro_database
    username: postgres
    password: root
  jpa:
    show-sql: false
    properties.hibernate:
      show_sql: false
      use_sql_comments: false
      format_sql: false
pomodoro:
  minimum-lifetime: ${POMODORO_MIN_LIFETIME:}
  standard:
    work: ${POMODORO_DAILY_AMOUNT_WORK:11}
    education: ${POMODORO_DAILY_AMOUNT_EDUCATION:3}
  tag:
    work:
      name: work
      calendar-id-color: 11
    education:
      name: education
      calendar-id-color: 5
  duration: ${POMODORO_DURATION:20}
  automatic-shutdown-duration: ${POMODORO_AUTOMATIC_SHUTDOWN_DURATION:25}
google-services:
  credentials-path: ${DRIVE_CREDENTIALS_PATH:}
  calendar:
    id:
      day-off: ${GOOGLE_CALENDAR_DAY_OFF_ID:}
      pomodoro: ${GOOGLE_CALENDAR_POMODORO_ID:}
    summary:
      day-off: ${GOOGLE_CALENDAR_DAY_OFF_SUMMARY:DayOff}
      pomodoro: ${GOOGLE_CALENDAR_POMODORO_SUMMARY:Pomodoro}
telegram:
  token: ${TELEGRAM_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}
audio-file:
  path: ${AUDIO_FILE_PATH:}
