server.port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pomodoro_database
    username: postgres
    password: root
  jpa:
    show-sql: false
    properties.hibernate:
      show_sql: false
      use_sql_comments: false
      format_sql: false
pomodoro:
  standard:
    work: ${POMODORO_DAILY_AMOUNT_WORK:11}
    education: ${POMODORO_DAILY_AMOUNT_EDUCATION:3}
  tag:
    work:
      name: work
      calendar-id-color: 11
    education:
      name: education
      calendar-id-color: 5
