server.port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pomodoro_database
    username: postgres
    password: root
  jpa:
    show-sql: false
    properties.hibernate:
      show_sql: false
      use_sql_comments: false
      format_sql: false
pomodoro:
  minimum-lifetime: ${POMODORO_MIN_LIFETIME:}
  standard:
    work: ${POMODORO_DAILY_AMOUNT_WORK:11}
    education: ${POMODORO_DAILY_AMOUNT_EDUCATION:3}
  duration: ${POMODORO_DURATION:20}
  automatic-shutdown-duration: ${POMODORO_AUTOMATIC_SHUTDOWN_DURATION:25}
telegram:
  token: ${TELEGRAM_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}
